#!/bin/bash

echo ""
echo "Help for dev setup :-"
echo ""
echo ""
echo "  Functionality :- Helps install/uninstall tools for coding projects."
echo ""
echo "  Syntax :- './[operation] [...tools]'"
echo ""
echo "  [operation] can be either of the following :-"
echo ""
echo "     > [install.sh] - For installing mentioned tools."
echo "     > [uninstall.sh] - For uninstalling mentioned tools."
echo ""
echo "  [...tools] :- Space seperated list of tools to be installed/uninstalled."
echo "                Can be either of the following :-"
echo "     > [python] - Python interpreter & Pip."
echo "     > [node] - NVM(Node version manager), the current version of NodeJS interpreter & NPM."
echo "     > [cpp] or [c++] - G++ compiler & other minor build tools."
echo "     > [project] - Custom sripts for creating and running projects with ease."
echo "     > [code] - Visual Studio Code."
echo ""
echo "     NOTE - You may install/uninstall all the tools by leaving the [...tools] argument"
echo "            blank. You should also note that uninstalling tools uninstalls the tools"
echo "            regardless of whether they were installed with the current tool. Uninstalling"
echo "            everything might uninstall tools that you might have installed yourself and"
echo "            need in the future."